apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  containers:
  - args:
    - '--accesslog=true'
    - '--log.level=info'
    - '--providers.docker=true'
    - '--api.dashboard=true'
    - '--api.insecure=true'
    - '--entrypoints.web.address=:80'
    - '--entrypoints.mariadb.address=:3306'
    image: docker.io/library/traefik:v3.0
    name: traefik
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 8080
      hostPort: 8070
      protocol: TCP
    volumeMounts:
    - mountPath: /var/run/docker.sock:z
      name: run-user-846632034-podman-podman.sock-host-1
  volumes:
  - hostPath:
      path: /run/user/846632034/podman/podman.sock
      type: File
    name: run-user-846632034-podman-podman.sock-host-1
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage
  labels:
    app: homepage
    traefik.enable: true
    traefik.http.routers.homepage.rule: PathPrefix(`/`)
    traefik.http.routers.homepage.entrypoints: web
    traefik.http.services.homepage.loadbalancer.server.port: 80
    traefik.http.routers.homepage.middlewares: strip-homepage-prefix
    traefik.http.middlewares.strip-homepage-prefix.stripPrefix.prefixes: /
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: homepage
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: apppo-html-host-0
    - mountPath: /etc/nginx/conf.d/default.conf
      name: apppo-default.conf-host-1
  dnsPolicy: Default
  volumes:
  - hostPath:
      path: ./html
      type: Directory
    name: apppo-html-host-0
  - hostPath:
      path: ./default.conf
      type: File
    name: apppo-default.conf-host-1
