services:
  traefik:
    image: docker.io/traefik:v3.0
    ports:
      - "80:80"
      - "8070:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    restart: unless-stopped
    networks:
      vpcbr:
        ipv4_address: 172.24.0.254
      docauposte2_vpcbr:
        ipv4_address: 172.21.0.254
      efnc_vpcbr:
        ipv4_address: 172.22.0.254
      opsign_vpcbr:
        ipv4_address: 172.23.0.254


  homepage:
    image: docker.io/nginx  # Example using nginx to serve custom error pages
    volumes:
      - ./html:/usr/share/nginx/html  # Mount the directory containing your error pages
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Mount a custom nginx config file
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=PathPrefix(`/`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.traefik-home.loadbalancer.server.port=80"
      - "traefik.http.routers.homepage.middlewares=strip-homepage-prefix"
      - "traefik.http.middlewares.strip-homepage-prefix.stripPrefix.prefixes=/"
    networks:
      vpcbr:
        ipv4_address:  172.24.0.253


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
  docauposte2_vpcbr:
    external: true
  efnc_vpcbr:
    external: true
  opsign_vpcbr:
    external: true