version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      docauposte2_vpcbr:
        ipv4_address: 172.21.0.254
      efnc_vpcbr:
        ipv4_address: 172.22.0.254
      vpcbr:
        ipv4_address: 172.23.0.254


  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.example
      - VIRTUAL_PORT=8000
    networks:
      docauposte2_vpcbr:
        ipv4_address: 172.21.0.253
      efnc_vpcbr:
        ipv4_address: 172.22.0.253
      vpcbr:
        ipv4_address: 172.23.0.253

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
  docauposte2_vpcbr:
   external: true
  efnc_vpcbr:
    external: true
     