version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "8070:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      vpcbr:
        ipv4_address: 172.24.0.254

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
  docauposte2_vpcbr:
   external: true
  efnc_vpcbr:
    external: true
  polyvalencefontaine_vpcbr:
    external: true