apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  containers:
  - args:
    - '--accesslog=true'
    - '--log.level=info'
    - '--providers.docker=true'
    - '--api.dashboard=true'
    - '--api.insecure=true'
    - '--entrypoints.web.address=:80'
    - '--entrypoints.mariadb.address=:3306'
    image: docker.io/library/traefik:v3.0
    name: traefik
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 8080
      hostPort: 8070
      protocol: TCP
    volumeMounts:
    - mountPath: /var/run/docker.sock:z
      name: run-user-846632034-podman-podman.sock-host-1
  volumes:
  - hostPath:
      path: /run/user/846632034/podman/podman.sock
      type: File
    name: run-user-846632034-podman-podman.sock-host-1