apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  containers:
  - image: docker.io/library/traefik:v3.0
    name: traefik
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 8080
      hostPort: 8070
      protocol: TCP
    volumeMounts:
    - mountPath: /var/run/docker.sock:z
      name: run-user-podman.sock
    - mountPath: /etc/traefik/traefik.yml
      name: traefik-config
      readOnly: true
  volumes:
  - hostPath:
      path: ${XDG_RUNTIME_DIR}/podman/podman.sock
      type: File
    name: run-user-podman.sock
  - hostPath:
      path: ./traefik.yml
      type: File
    name: traefik-config
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage
  labels:
    app: homepage
    traefik.enable: true
    traefik.http.routers.homepage.rule: PathPrefix(`/`)
    traefik.http.routers.homepage.entrypoints: web
    traefik.http.routers.homepage.middlewares: strip-homepage-prefix
    traefik.http.services.homepage.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-homepage-prefix.stripPrefix.prefixes: /
spec:
  containers:
  - name: homepage
    image: docker.io/library/nginx:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        chmod -R 755 /usr/share/nginx/html; 
        chown -R nginx:nginx /usr/share/nginx/html; 
        nginx -g 'daemon off;'
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: apppo-html
    - mountPath: /etc/nginx/conf.d/default.conf
      name: apppo-default.conf
  dnsPolicy: Default
  volumes:
  - hostPath:
      path: ./html
      type: Directory
    name: apppo-html
  - hostPath:
      path: ./default.conf
      type: File
    name: apppo-default.conf
