apiVersion: v1
kind: LimitRange
metadata:
  name: traefik-proxy-pod-limits-range
  namespace: traefik-proxy-pod-limits
spec:
  limits:
    - defaultRequest:
        memory: 4000Mi
        ephemeral-storage: 5000Mi
        cpu: 4
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: traefik-proxy-pod
  namespace: traefik-proxy-pod-limits
  labels:
    app: traefik-proxy
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
    - image: docker.io/library/traefik:v3.3.3
      name: proxy
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
      volumeMounts:
        - mountPath: /var/run/docker.sock:z
          name: run-user-podman.sock
          readOnly: true
        - mountPath: /etc/traefik/traefik.yml
          name: traefik-config
          readOnly: true
        - mountPath: /etc/traefik/dynamic.yml
          name: dynamic-config
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime-settings
          readOnly: true
        - mountPath: /certs
          name: tls-certs
          readOnly: true
      resources:
        limits:
          memory: 4000Mi
          ephemeral-storage: 5000Mi
        requests:
          cpu: 4
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ${XDG_RUNTIME_DIR}/podman/podman.sock
        type: File
      name: run-user-podman.sock
    - hostPath:
        path: ${PWD}/traefik.yml
        type: File
      name: traefik-config
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
    - hostPath:
        path: ${PWD}/certs
        type: Directory
      name: tls-certs
    - hostPath:
        path: ${PWD}/dynamic.yml
        type: File
      name: dynamic-config
---
apiVersion: v1
kind: LimitRange
metadata:
  name: homepage-nginx-limits-range
  namespace: homepage-nginx-limits
spec:
  limits:
    - defaultRequest:
        memory: 200Mi
        ephemeral-storage: 50Mi
        cpu: 0.5
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-nginx-pod
  namespace: homepage-nginx-limits
  labels:
    app: homepage-nginx
    traefik.enable: true
    traefik.http.routers.homepage-nginx.rule: "Host(`${DOMAIN_NAME}.corp.ponet`) && PathPrefix(`/`) || Host(`${HOSTNAME}.ad.ponet`) && PathPrefix(`/`)"
    traefik.http.routers.homepage-nginx.entrypoints: websecure
    traefik.http.routers.homepage-nginx.tls: true
    traefik.http.routers.homepage-nginx.middlewares: strip-homepage-nginx-prefix
    traefik.http.services.homepage-nginx.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-homepage-nginx-prefix.stripPrefix.prefixes: /
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
    - name: nginx
      image: docker.io/library/nginx:stable-alpine3.20
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod -R 755 /usr/share/nginx/html; 
          chown -R nginx:nginx /usr/share/nginx/html; 
          nginx -g 'daemon off;'
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: apppo-html
        - mountPath: /etc/nginx/conf.d/default.conf
          name: apppo-default.conf
        - mountPath: /etc/localtime
          name: localtime-settings
      resources:
        limits:
          memory: 200Mi
          ephemeral-storage: 500Mi
        requests:
          cpu: 0.5
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ${PWD}/html
        type: Directory
      name: apppo-html
    - hostPath:
        path: ${PWD}/default.conf
        type: File
      name: apppo-default.conf
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
