apiVersion: v1
kind: Pod
metadata:
  name: traefik-proxy-pod
  labels:
    app: traefik-proxy
spec:
  restartPolicy: Always
  containers:
    - image: docker.io/library/traefik:v3.0
      name: proxy
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        - containerPort: 8080
          hostPort: 8070
          protocol: TCP
      volumeMounts:
        - mountPath: /var/run/docker.sock:z
          name: run-user-podman.sock
        - mountPath: /etc/traefik/traefik.yml
          name: traefik-config
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime-settings
        - mountPath: /etc/traefik/acme/acme.json
          name: traefik-acme
        # - mountPath: /etc/traefik/dynamic_conf.yml
        #   subPath: dynamic_conf.yml
        #   name: traefik-dynamic-config
        #   readOnly: true
        # - mountPath: /certs
        #   name: tls-certs
        #   readOnly: true
  volumes:
    - hostPath:
        path: ${XDG_RUNTIME_DIR}/podman/podman.sock
        type: File
      name: run-user-podman.sock
    - hostPath:
        path: ${PWD}/traefik.yml
        type: File
      name: traefik-config
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
    - hostPath:
        path: ./acme.json
        type: FileOrCreate
      name: traefik-acme
    # - hostPath:
    #     path: ./dynamic_conf.yml
    #     type: File
    #   name: traefik-dynamic-config
    # - hostPath:
    #     path: ./certs
    #     type: Directory
    #   name: tls-certs
---
apiVersion: v1
kind: LimitRange
metadata:
  name: homepage-nginx-limits-range
  namespace: homepage-nginx-limits
spec:
  limits:
    - type: Container
      default:
        memory: 200Mi
        ephemeral-storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-nginx-pod
  namespace: homepage-nginx-limits
  labels:
    app: homepage-nginx
    traefik.enable: true
    traefik.http.routers.homepage-nginx.rule: "Host(`${HOSTNAME}`) && PathPrefix(`/`)"
    traefik.http.routers.homepage-nginx.entrypoints: websecure
    traefik.http.routers.homepage-nginx.tls: true
    traefik.http.routers.homepage-nginx.tls.certresolver: myresolver
    traefik.http.routers.homepage-nginx.middlewares: strip-homepage-nginx-prefix
    traefik.http.services.homepage-nginx.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-homepage-nginx-prefix.stripPrefix.prefixes: /
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod -R 755 /usr/share/nginx/html; 
          chown -R nginx:nginx /usr/share/nginx/html; 
          nginx -g 'daemon off;'
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: apppo-html
        - mountPath: /etc/nginx/conf.d/default.conf
          name: apppo-default.conf
        - mountPath: /etc/localtime
          name: localtime-settings
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ${PWD}/html
        type: Directory
      name: apppo-html
    - hostPath:
        path: ${PWD}/default.conf
        type: File
      name: apppo-default.conf
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
