## traefik.yml
# Docker configuration backend
providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
api:
  dashboard: true
  # Secure the dashboard (replace with your chosen username and password)
  # insecure: true
#Entrypoint configuration
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver   # Use the default certificate resolver

# # Define the default TLS store with your certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: "/certs/lan-apps.ad.ponet.pem"
#         keyFile: "/certs/lan-apps.ad.ponet.key"

