## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: true
# providers:
#   file:
#     filename: /etc/traefik/dynamic_conf.yml
#     watch: true

api:
  dashboard: true
  # Secure the dashboard (replace with your chosen username and password)
  insecure: true

#Entrypoint configuration
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        # Remove certResolver since we're using our own certs
        certResolver: myresolver

# tls:
#   certificates:
#     - certFile: "/certs/yourcert.crt"
#       keyFile: "/certs/yourkey.key"

# Remove certificatesResolvers if not using Let's Encrypt
certificatesResolvers:
  myresolver:
    acme:
      email: florian.dkhissi@opmobility.com
      storage:
        /etc/traefik/acme/acme.json
        # Remove or comment out the staging server URL
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web
