## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: true

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

#Entrypoint configuration
entryPoints:
  web:
    address: ":80"
  web-https:
    address: ":443"
  # mariadb:
  #   address: ":3306"
#   smtp:
#     address: ":25"

# tcp:
#   routers:
#     smtp-router:
#       entryPoints:
#         - smtp
#       service: smtp-service
#   services:
#     smtp-service:
#       loadBalancer:
#         servers:
#           - address: "smtp.corp.ponet:25"

