## traefik.yml
# Docker configuration backend
providers:
  docker:
    exposedByDefault: true
api:
  dashboard: true
  # Secure the dashboard (replace with your chosen username and password)
  insecure: true
#Entrypoint configuration
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
        # Remove certResolver since we're using our own certs
#         certResolver: myresolver
# # Remove certificatesResolvers if not using Let's Encrypt
certificatesResolvers:
  myresolver:
    acme:
      email: florian.dkhissi@opmobility.com
      storage:
        /etc/traefik/acme/acme.json
        # Remove or comment out the staging server URL
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web
tls:
  certificates:
    - certFile: "/certs/lan-apps.ad.ponet.pem"
      keyFile: "/certs/lan-apps.ad.ponet.key"
