## traefik.yml

# Docker configuration backend
# providers:
#   docker: 
#     # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
#     # exposedByDefault: false
#     network: docauposte2_vpcbr

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

#Entrypoint configuration
entryPoints:
  web:
    address: ":80"

http:
  routers:
    to-docauposte:
      rule: "Host(`docauposte`) && PathPrefix(`/docauposte/`)"
      service: to-docauposte
      entryPoints:
        - web
        
services: